### ISSUE TITLE
Source Code License

### ISSUE THREAD

**Issue by CanIGetaPR** [darthmall/webc-eleventy-test#9]
Hey there! Thanks for your wonderful webc example. I noticed there is no license with the source code. Do you give any permissions to copy and use the website code?

If you would like some license suggestions, I suggest MIT if you'd like anyone to do anything with it, or MPL if you'd like derivatives to remain open source, but not require projects using the code to become open source as a result.

**Comment by darthmall** [comment]
@CanIGetaPR Thanks for the heads up. I’d put the license in package.json, but I forgot to include the license file.

The code is licensed under the AGPL license, all of the content in the articles is creative commons. I updated the project with that information.
